server {
    listen 80;
    server_name traapp.online www.traapp.online traapp.ru www.traapp.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name traapp.online www.traapp.online traapp.ru www.traapp.ru;

    ssl_certificate     /etc/letsencrypt/live/traapp.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/traapp.online/privkey.pem;

    location /api/ {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
